sudo: false
language: node_js
node_js:
  - "stable"
  - 6
  - 4

env:
  global:
    COVERALLS_PARALLEL: true

cache: yarn

script: "yarn test -- --coverage"

after_success: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
